# -*- mode: ruby -*-
# vi: set ft=ruby :
# IP's of servers have to be in the same network range as 
ENV['VAGRANT_NO_PARALLEL'] = 'yes'

Vagrant.configure(2) do |config|


  path = ENV["VAGRANT_HOME"]
  controller_ip = "192.168.56.21"
  storage_ip = "192.168.56.31"
  compute1_ip = "192.168.56.41"
  chrony_ip = "192.0.0.0/24"
  default_user = "openstack"
  default_password = "openstack"
  ssh_user = "vagrant"
  ssh_password = "vagrant"

 # Vagrant controller
  config.vm.define "controller" do |controller|
    controller.vm.box = "bento/ubuntu-16.04"
    controller.vm.hostname = "controller-vagrant"
    # create one network interface: , adapter: "1" but ssh will not connect
    # IP is RANDOM  when type dhcp is set
    # REMEMBER INTERFACE NEED TO BE MODIFIED WHEN CHANGING HOST
    #controller.vm.network "private_network", virtualbox__intnet: "VirtualBox Host-Only Ethernet Adapter #2", ip: controller_ip, :adapter => 2
    controller.vm.network "private_network", ip: controller_ip
    
    controller.vm.provision "file", source: "files", destination: "~/files"
    controller.persistent_storage.enabled = true
    controller.persistent_storage.location = "~/controller.vdi"
    controller.persistent_storage.size = 25000
    #controller.persistent_storage.mountname = 'data'
    #controller.persistent_storage.filesystem = 'ext4'
    #controller.persistent_storage.mountpoint = '/mnt/data'
    #controller.persistent_storage.volgroupname = 'cinder-volumes'
    controller.vm.provider "virtualbox" do |v|
      v.name = "controller"
      v.memory = 8192
      v.cpus = 4
      v.customize ["modifyvm", :id, "--nic3",  "natnetwork", "--nat-network3", "ProviderNetwork1", "--nicpromisc3", "allow-all" ]
      v.customize ["modifyvm", :id, "--nic4", "natnetwork", "--nat-network4", "NatNetwork1" ]
    end
    ssh_pub_key = File.readlines("#{Dir.home}/.ssh/id_rsa.pub").first.strip

    #openstack.vm.provision "shell",
    #  run: "always",
    #  inline: "route add default gw 192.168.86.1 eth1"
    

    controller.vm.provision "shell", path: "bootstrap.sh", :args => [ssh_pub_key, controller_ip, storage_ip, compute1_ip, controller_ip ]
    controller.vm.provision :reload
    controller.vm.provision "shell", path: "chrony.sh", :args => ["yes", chrony_ip]
    controller.vm.provision :reload
    controller.vm.provision "shell", path: "software.sh"
    controller.vm.provision "shell", path: "controller.sh", :args => [controller_ip, default_user, default_password]

  end


  config.vm.define "storage" do |storage|
    storage.vm.box = "bento/ubuntu-16.04"
    storage.vm.hostname = "storage"
    storage.vm.network "private_network", ip: storage_ip
    storage.vm.provision "file", source: "files", destination: "~/files"
    storage.persistent_storage.enabled = true
    storage.persistent_storage.location = "~/storage.vdi"
    storage.persistent_storage.size = 25000
    #storage.persistent_storage.mountname = 'data'
    #storage.persistent_storage.filesystem = 'ext4'
    #storage.persistent_storage.mountpoint = '/mnt/data'
    # im using LVM
    storage.persistent_storage.partition = false
    #storage.persistent_storage.volgroupname = 'cinder-volumes'
    storage.vm.provider "virtualbox" do |v|
      v.name = "openstackstorage"
      v.memory = 8192
      v.cpus = 4
      v.customize ["modifyvm", :id, "--nic3",  "natnetwork", "--nat-network3", "ProviderNetwork1", "--nicpromisc3", "allow-all" ]
      v.customize ["modifyvm", :id, "--nic4", "natnetwork", "--nat-network4", "NatNetwork1" ]
    end
    ssh_pub_key = File.readlines("#{Dir.home}/.ssh/id_rsa.pub").first.strip

    #openstack.vm.provision "shell",
    #  run: "always",
    #  inline: "route add default gw 192.168.86.1 eth1"
    

    storage.vm.provision "shell", path: "bootstrap.sh", :args => [ssh_pub_key, controller_ip, storage_ip, compute1_ip, storage_ip ]
    storage.vm.provision :reload
    storage.vm.provision "shell", path: "chrony.sh", :args => ["no", chrony_ip]
    storage.vm.provision :reload
    storage.vm.provision "shell", path: "software.sh"
    storage.vm.provision "shell", path: "storage.sh", :args => [storage_ip, default_user, default_password, ssh_user, ssh_password]
    


  end

  
  config.vm.define "compute1" do |compute1|
    compute1.vm.box = "bento/ubuntu-16.04"
    compute1.vm.hostname = "compute1"
    compute1.vm.network "private_network", ip: compute1_ip
    compute1.vm.provision "file", source: "files", destination: "~/files"
    compute1.persistent_storage.enabled = true
    compute1.persistent_storage.location = "~/compute1.vdi"
    compute1.persistent_storage.size = 25000
    #compute1.persistent_storage.mountname = 'data'
    #compute1.persistent_storage.filesystem = 'ext4'
    #compute1.persistent_storage.mountpoint = '/mnt/data'
    #compute1.persistent_storage.volgroupname = 'cinder-volumes'
    compute1.vm.provider "virtualbox" do |v|
      v.name = "openstackcompute1"
      v.memory = 36.864
      v.cpus = 8
      v.customize ["modifyvm", :id, "--nic3",  "natnetwork", "--nat-network3", "ProviderNetwork1", "--nicpromisc3", "allow-all" ]
      v.customize ["modifyvm", :id, "--nic4", "natnetwork", "--nat-network4", "NatNetwork1" ]
    end
    ssh_pub_key = File.readlines("#{Dir.home}/.ssh/id_rsa.pub").first.strip

    #openstack.vm.provision "shell",
    #  run: "always",
    #  inline: "route add default gw 192.168.86.1 eth1"
    
    compute1.vm.provision "shell", path: "bootstrap.sh", :args => [ssh_pub_key, controller_ip, storage_ip, compute1_ip, compute1_ip ]
    compute1.vm.provision :reload
    compute1.vm.provision "shell", path: "chrony.sh", :args => ["no", chrony_ip]
    compute1.vm.provision :reload
    compute1.vm.provision "shell", path: "software.sh"
    compute1.vm.provision "shell", path: "compute.sh", :args => [compute1_ip, default_user, default_password, ssh_user, ssh_password]

  end


  # TODO How to call Nove register nodes command
  #su -s /bin/sh -c "nova-manage cell_v2 discover_hosts --verbose" nova



end
