# -*- mode: ruby -*-
# vi: set ft=ruby :

boxes = [
    {
        :name => "elk",
        :eth1 => "192.29.16.40",
        :mem => "3024",
        :cpu => "1"
    },
   
]

Vagrant.configure("2") do |config|

# config.ssh.forward_agent = true
# yum bento/ubuntu-18.04
  config.vm.box = "bento/ubuntu-18.04"
  boxes.each do |opts|
    config.vm.define opts[:name] do |config|
      config.vm.hostname = opts[:name]
      config.vm.synced_folder ".", "/vagrant", type: "virtualbox"
      config.vm.network :private_network, ip: opts[:eth1]
      config.vm.network "forwarded_port", guest: 9200, host_ip: "127.0.0.1", host: 9200, id: "elasticsearch"
      config.vm.network "forwarded_port", guest: 5601, host_ip: "127.0.0.1", host: 5601, id: "Kibana"
      config.vm.provider "virtualbox" do |v|
        v.customize ["modifyvm", :id, "--memory", opts[:mem]]
        v.customize ["modifyvm", :id, "--cpus", opts[:cpu]]
        # suggested speedup for network performance through faster name resolution
        v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
        # suggested speedup by enabing multiple cpu cores, figured it would be by default
        v.customize ["modifyvm", :id, "--ioapic", "on"]
      end
      ssh_pub_key = File.readlines("#{Dir.home}/.ssh/id_rsa.pub").first.strip
      config.vm.provision "shell", path: "bootstrap.sh", :args => [ssh_pub_key]
     
    end
  end

end

 
