# -*- mode: ruby -*-
# vi: set ft=ruby :
# IP's of servers have to be in the same network range as 
ENV['VAGRANT_NO_PARALLEL'] = 'yes'

Vagrant.configure(2) do |config|

  config.vm.provision "shell", path: "bootstrap.sh"
  path = ENV["VAGRANT_HOME"]

  # Kubernetes Master Server
  # NOTE: requires: vagrant plugin install vagrant-persistent-storage
  config.vm.define "kmaster" do |kmaster|
    kmaster.vm.box = "bento/ubuntu-18.04"
    kmaster.vm.hostname = "kmaster.hspo.com"
    # create one network interface: , adapter: "1" but ssh will not connect
    kmaster.vm.network "public_network", ip: "192.168.86.150" 
    kmaster.vm.provision "file", source: "kube-flannel.yaml", destination: "kube-flannel.yaml"
    kmaster.vm.provision "file", source: "files", destination: "~/files"
    kmaster.persistent_storage.enabled = true
    kmaster.persistent_storage.location = "~/elk/masterhdd.vdi"
    kmaster.persistent_storage.size = 10000
    kmaster.persistent_storage.mountname = 'data'
    kmaster.persistent_storage.filesystem = 'ext4'
    kmaster.persistent_storage.mountpoint = '/mnt/data'
    kmaster.persistent_storage.volgroupname = 'vg_data'
    
    kmaster.vm.provider "virtualbox" do |v|
      v.name = "kmaster"
      v.memory = 4048
      v.cpus = 2
    end
    ssh_pub_key = File.readlines("#{Dir.home}/.ssh/id_rsa.pub").first.strip
    kmaster.vm.provision "shell", path: "bootstrap_kmaster.sh", :args => [ssh_pub_key]
  end
   
  NodeCount = 2

  # Kubernetes Worker Nodes
  (1..NodeCount).each do |i|
    config.vm.define "kworker#{i}" do |workernode|
      ip_addr = "192.168.86.15#{i}"
      workernode.vm.box = "bento/ubuntu-18.04"
      workernode.vm.hostname = "kworker#{i}.hspo.com"
      workernode.vm.network "public_network", ip: "#{ip_addr}"
      workernode.persistent_storage.enabled = true
      workernode.persistent_storage.location = "~/elk/worker#{i}hdd.vdi"
      workernode.persistent_storage.size = 10000
      workernode.persistent_storage.mountname = 'data'
      workernode.persistent_storage.filesystem = 'ext4'
      workernode.persistent_storage.mountpoint = '/mnt/data'
      workernode.persistent_storage.volgroupname = 'vg_data'
      workernode.vm.provider "virtualbox" do |v|
        v.name = "kworker#{i}"
        v.memory = 6096
        v.cpus = 2
      end
      ssh_pub_key = File.readlines("#{Dir.home}/.ssh/id_rsa.pub").first.strip
      
      workernode.vm.provision "shell", path: "bootstrap_kworker.sh" , :args => [ssh_pub_key, ip_addr]
    end
  end

end
