# -*- mode: ruby -*-
# vi: set ft=ruby :

boxes = [
    {
        :name => "broker1",
        :eth1 => "192.29.16.20",
        :mem => "1024",
        :cpu => "1"
    },
    {
        :name => "broker2",
        :eth1 => "192.29.16.21",
        :mem => "1024",
        :cpu => "1"
    },
    {
        :name => "broker3",
        :eth1 => "192.29.16.22",
        :mem => "1024",
        :cpu => "1"
    },
]

Vagrant.configure("2") do |config|

# config.ssh.forward_agent = true
  config.vm.box = "ubuntu/trusty64"
  boxes.each do |opts|
    config.vm.define opts[:name] do |config|
      config.vm.hostname = opts[:name]
      config.vm.synced_folder ".", "/vagrant", type: "virtualbox"
      config.vm.network :private_network, ip: opts[:eth1]
      config.vm.provider "virtualbox" do |v|
        v.customize ["modifyvm", :id, "--memory", opts[:mem]]
        v.customize ["modifyvm", :id, "--cpus", opts[:cpu]]
        # suggested speedup for network performance through faster name resolution
        v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
        # suggested speedup by enabing multiple cpu cores, figured it would be by default
        v.customize ["modifyvm", :id, "--ioapic", "on"]
      end
      ssh_pub_key = File.readlines("#{Dir.home}/.ssh/id_rsa.pub").first.strip
      config.vm.provision "shell", path: "bootstrap.sh", :args => [ssh_pub_key]
    end
  end

end

#    # zookeeper1 
#    config.vm.define "zookeeper1" do |broker1|
#     broker1.vm.box = "ubuntu/trusty64"
#     broker1.vm.hostname = "zookeeper01.hspo.dk"
#     broker1.vm.network "private_network", ip: "192.29.16.30"
  
#     broker1.vm.provider "virtualbox" do |v|
#       v.name = "zookeeper01.hspo.dk"
#       v.memory = 4096
#       v.cpus = 2
#     end
#     ssh_pub_key = File.readlines("#{Dir.home}/.ssh/id_rsa.pub").first.strip
#     broker1.vm.provision "shell", path: "bootstrap.sh", :args => [ssh_pub_key]
#   end
# end
 
  # config.vm.box = "ubuntu/trusty64" 
  # config.vm.network "private_network", ip: "192.29.16.20" 
  # config.vm.hostname ="broker01.hspo.dk"
  # # Enable ssh forward agent
  # config.ssh.forward_agent = true
 
  

  # config.vm.provider "virtualbox" do |vb|
  #   vb.memory = 4096      # Memory size in M.
  #   vb.cpus   = 2         # Number of vCPUs
  #   vb.name   = "broker01.hspo.dk"   # VM name.
    
  # end

  # config.vm.provision "shell" do |s|
  #   ssh_pub_key = File.readlines("#{Dir.home}/.ssh/id_rsa.pub").first.strip
  #   s.inline = <<-SHELL
  #     sudo apt-get update
  #     sudo apt-get install -y  dnsutils
  #     sudo apt-get install -y curl
  #     sudo apt-add-repository ppa:ansible/ansible -y
  #     sudo apt-get update
  #     sudo apt-get install -y ansible
  #     sudo apt-get install xauth
  #     sudo sed -i 's/XKBLAYOUT=.*/XKBLAYOUT="dk"/g' /etc/default/keyboard
  #     sudo useradd -m hspo
  #     usermod -aG sudo hspo
  #     sudo mkdir /home/hspo/.ssh
  #     sudo chown -R hspo:hspo /home/hspo/.ssh
  #     sudo echo #{ssh_pub_key} >> /home/hspo/.ssh/authorized_keys
  #     echo #{ssh_pub_key} >> /root/.ssh/authorized_keys
  #     sudo echo "hspo ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers.d/hspo
  #   SHELL
  # end


  
  # end
