
# -*- mode: ruby -*-
# vi: set ft=ruby :
# IP's of servers have to be in the same network range as 
ENV['VAGRANT_NO_PARALLEL'] = 'yes'

Vagrant.configure(2) do |config|
  
  ssh_pub_key = File.readlines("#{Dir.home}/.ssh/id_rsa.pub").first.strip
  config.vm.provision "shell", path: "bootstrap.sh" , :args => [ssh_pub_key]
  config.vm.provision :reload
  
  
  # path = ENV["VAGRANT_HOME"]

  # config.vm.define "nfs_server_vag" do |nfs|
  #   nfs_ip_addr = "192.168.1.20"
  #   nfs.vm.box = "bento/ubuntu-20.04"
  #   nfs.vm.hostname = "nfsserver.hspo.com"
  #   # create one network interface: , adapter: "1" but ssh will not connect
  #   nfs.vm.network "public_network", ip: "#{nfs_ip_addr}" 

  #   nfs.persistent_storage.enabled = true
  #   nfs.persistent_storage.location = "~/kubernetes/nfsserverhdd.vdi"
  #   # 200 GB in MB
  #   nfs.persistent_storage.size = 400000
  #   nfs.persistent_storage.mountname = 'data'
  #   nfs.persistent_storage.filesystem = 'xfs'
  #   nfs.persistent_storage.mountpoint = '/data/k8s'
  #   nfs.persistent_storage.volgroupname = 'k8s_data'
    
  #   nfs.vm.provider "virtualbox" do |v|
  #     v.name = "nfsserver_vag"
  #     v.memory = 6048
  #     v.cpus = 4
  #   end
  #   nfs.vm.provision "shell", path: "bootstrap_nfsserver.sh ", :args => [nfs_ip_addr]
  # end

  # Kubernetes Master Server
  # NOTE: requires: vagrant plugin install vagrant-persistent-storage
  config.vm.define "kmaster_vag" do |kmaster|
    master_ip_addr = "192.168.1.150"
    kmaster.vm.box = "bento/ubuntu-20.04"
    kmaster.vm.hostname = "kmaster.hspo.com"
    # create one network interface: , adapter: "1" but ssh will not connect
    kmaster.vm.network "public_network", ip: "#{master_ip_addr}", bridge: "Intel(R) Ethernet Controller I226-V" 
    


    # TODO Configure Allow all
    #kmaster.customize ["modifyvm", :id, "--nic1",  "bridgeadapter", "--nat-network2", "ProviderNetwork1", "--nicpromisc3", "allow-all" ]
    kmaster.vm.provision "file", source: "kube-flannel.yaml", destination: "kube-flannel.yaml"
    kmaster.vm.provision "file", source: "files", destination: "~/files"
    kmaster.persistent_storage.enabled = true
    kmaster.persistent_storage.location = "~/kubernetes/masterhdd.vdi"
    # 20 GB in MB
    kmaster.persistent_storage.size = 20000
    kmaster.persistent_storage.mountname = 'data'
    kmaster.persistent_storage.filesystem = 'ext4'
    kmaster.persistent_storage.mountpoint = '/mnt/data'
    kmaster.persistent_storage.volgroupname = 'vg_data'
    
    kmaster.vm.provider "virtualbox" do |v|
      v.name = "kmaster_k3s_vag"
      v.memory = 8096
      v.cpus = 4
    end
    kmaster.vm.provision "shell", path: "init_k3s_nodes.sh" 
    kmaster.vm.provision "shell", path: "bootstrap_kmaster.sh ", :args => [master_ip_addr]
    kmaster.vm.provision "shell", inline: <<-SHELL
      sudo cp /var/lib/rancher/k3s/server/node-token /vagrant/node-token
      sudo chown vagrant:vagrant /vagrant/node-token
      sudo chmod 600 /vagrant/node-token
      echo "node-token GENERATED"
    SHELL


  end
   
  NodeCount = 3

  
  

  # Kubernetes Worker Nodes
  (1..NodeCount).each do |i|
  # token_path = File.join(__dir__, "node-token")
  # K3S_NODE_TOKEN = File.exist?(token_path) ? File.read(token_path).strip : nil
  # puts "K3S_NODE_TOKEN=#{K3S_NODE_TOKEN || '(not found yet)'}"
    config.vm.define "kworker#{i}_vag" do |workernode|
      ip_addr = "192.168.1.15#{i}"
      workernode.vm.box = "bento/ubuntu-20.04"
      workernode.vm.hostname = "kworker#{i}.hspo.com"
      workernode.vm.network "public_network", ip: "#{ip_addr}" , bridge: "Intel(R) Ethernet Controller I226-V" 
      workernode.persistent_storage.enabled = true
      workernode.persistent_storage.location = "~/kubernetes/worker#{i}hdd.vdi"
      workernode.persistent_storage.size = 20000
      workernode.persistent_storage.mountname = 'data'
      workernode.persistent_storage.filesystem = 'ext4'
      workernode.persistent_storage.mountpoint = '/mnt/data'
      workernode.persistent_storage.volgroupname = 'vg_data'
      workernode.vm.provider "virtualbox" do |v|
        v.name = "kworker_ks3_vag#{i}"
        v.memory = 8096
        v.cpus = 6
      end
      ssh_pub_key = File.readlines("#{Dir.home}/.ssh/id_rsa.pub").first.strip
      workernode.vm.provision "shell", path: "init_k3s_nodes.sh" 
      #workernode.vm.provision "shell", path: "bootstrap_kworker.sh" , :args => ["192.168.1.150", ip_addr , K3S_NODE_TOKEN, "eth1"]
      workernode.vm.provision "shell", path: "bootstrap_kworker.sh" , :args => ["192.168.1.150", ip_addr, "/vagrant/node-token", "eth1"]
      if i == NodeCount
        workernode.vm.provision "shell", inline: "rm -f /vagrant/node-token"
      end
    end
  end

  

end
