kind: PersistentVolume
apiVersion: v1
metadata:
  name: elk-pv
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"