apiVersion: v1
kind: Namespace
metadata:
  name: cni-test
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: netshoot
  namespace: cni-test
spec:
  selector:
    matchLabels:
      app: netshoot
  template:
    metadata:
      labels:
        app: netshoot
    spec:
      hostNetwork: false
      containers:
      - name: netshoot
        image: nicolaka/netshoot:latest
        command: ["sleep","360000"]
---
apiVersion: v1
kind: Service
metadata:
  name: whoami
  namespace: cni-test
spec:
  selector:
    app: whoami
  ports:
  - name: http
    port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami
  namespace: cni-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      labels:
        app: whoami
    spec:
      containers:
      - name: whoami
        image: traefik/whoami:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: whoami
  namespace: cni-test
spec:
  selector:
    app: whoami
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: whoami
  namespace: cni-test
spec:
  ingressClassName: traefik
  rules:
  - host: whoami.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: whoami
            port:
              number: 80

